# Generated by Django 3.2.11 on 2022-04-28 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borough',
            fields=[
                ('boro_code', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot_Location',
            fields=[
                ('obj_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('loc_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('X', models.CharField(max_length=100)),
                ('Y', models.CharField(max_length=100)),
                ('activated', models.DateField(null=True)),
                ('bin', models.SmallIntegerField(null=True)),
                ('bbl', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('ntcaode', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('postcode', models.SmallIntegerField()),
                ('nta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('prov_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=70)),
                ('ssid', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50)),
                ('loc_type', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot_Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hotspot_location')),
                ('prov_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot_Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntacode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.neighborhood')),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hotspot_location')),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot_Borough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boro_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.borough')),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hotspot_location')),
            ],
        ),
    ]
