# Generated by Django 3.2.11 on 2022-04-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot_location',
            name='X',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotspot_location',
            name='Y',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotspot_location',
            name='activated',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hotspot_location',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotspot_location',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
