# Generated by Django 3.2.11 on 2022-04-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220430_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot_location',
            name='bbl',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotspot_location',
            name='bin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotspot_location',
            name='latitude',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotspot_location',
            name='longitude',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
