# Generated by Django 3.2.11 on 2022-04-30 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220430_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotspot_provider',
            name='id',
        ),
        migrations.AlterField(
            model_name='hotspot_provider',
            name='obj_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.hotspot_location'),
        ),
    ]
