# Generated by Django 3.2.11 on 2022-04-30 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220430_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot_borough',
            name='obj_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.hotspot_location'),
        ),
        migrations.AlterField(
            model_name='hotspot_neighborhood',
            name='obj_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.hotspot_location'),
        ),
    ]
