# Generated by Django 3.2.11 on 2022-04-30 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220430_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot_provider',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotspot_provider',
            name='obj_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.hotspot_location'),
        ),
    ]
