# Generated by Django 3.2.11 on 2022-05-04 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220430_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='ntcaode',
            new_name='ntacode',
        ),
    ]
