# Generated by Django 3.2.11 on 2022-05-06 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='obj_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hotspot_location'),
        ),
    ]
